### ISSUE TITLE
Working, but has output issues

### ISSUE THREAD

**Issue by grovercoder** [JayXT/RecordAudioOutput#1]
I am running Debian 12 with KDE.  Both scripts are working, but  both exhibit issues with the generated file.

The `record-audio-output` script records a file with the sound set to something very low.  I can just make out that the audio is there, but can't really hear it. 

The `record-audio-output-pw` script records the file, and the volume seems right, but playback is at about 95% speed.  Just enough to say this sounds a little slow (almost like dragging your finger lightly on a record player...)

I've played with the parec, pw-record, and lame settings to try to address these issues, but no luck yet.  

I suspect the issue is not the script but something with my system.  It is a development box and gets all kinds of abuse.  I'll continue playing, and and report back if I solve the issue.

Thanks for the script.  I knew there had to be an "easier way" than trying to hack some stream.

**Comment by grovercoder** [comment]
Premature post.  A few moments later I seem to have solved the issue.

First, the pacmd command does not work for me it returns 'No PulseAudio daemon running, or not running as session daemon.'
But `pactl list sinks` does work.  This nicely includes a "Monitor Source" line with a value that can be used verbatim.

Next, I cut/paste the discovered Monitor Source string into the script instead of using DEFAULT_SINK or DEFAULT_MONITOR.  

My volume issue disappeared and the speed seems correct.  I have not resolved the speed issue with the _pw script yet - but I have a working solution now.

Thanks again.

**Comment by JayXT** [comment]
I'm glad the solution helped you, @grovercoder. From my side, I'd like to add that I had a problem with pgrep when running the script using a shortcut on KDE Plasma:
https://discuss.kde.org/t/pgrep-doesnt-work-in-wayland-session/13686

On Xfce and GNOME it worked pretty good with no issues like this.

**Comment by JayXT** [comment]
BTW, on PipeWire you could use `wpctl status` to find the id of the output device. Then using its number will explicitly set the output source for recording.

**Comment by JayXT** [comment]
@grovercoder, I've noticed one interesting thing. Sometimes, especially on weaker CPUs or with PipeWire lame utility tends to record slighly distorted audio. You might also consider replacing lame with opusenc from opus-tools package on Debian. In such case the following script will record audio in opus format:
```#!/bin/sh

if pgrep pw-record
then 
  # Stop recording audio
  pkill pw-record
else
  # Get the default WirePlumber sink (output device) ID
  targetSink=$(wpctl status | grep -oPm 1 '\*\s+\K\d+')

  # 5-character random string
  rand=$(cat /dev/urandom | tr -dc 'A-Z0-9' | fold -w 7 | head -n 1)

  # Construct filename
  filename="$(xdg-user-dir DOWNLOAD)/out_${rand}.opus"

  # Record audio to the file
  # pw-record --target=$targetSink - | lame -r -V7 - $filename
  pw-record --target=$targetSink - | opusenc --raw - $filename

  # Copy the file to the clipboard
  echo "file://${filename}"|xclip -i -sel c -t text/uri-list```
